<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transaction Reports</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Arial', sans-serif;
      font-size: 12px;
      color: #333;
      padding: 20px;
    }

    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 2px solid #333;
      padding-bottom: 15px;
    }

    .header h1 {
      font-size: 24px;
      margin-bottom: 5px;
    }

    .header p {
      font-size: 14px;
      color: #666;
    }

    .info-section {
      margin-bottom: 20px;
    }

    .info-section p {
      margin-bottom: 5px;
    }

    .info-section strong {
      display: inline-block;
      width: 120px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }

    table thead {
      background-color: #f5f5f5;
    }

    table th {
      padding: 10px;
      text-align: left;
      border: 1px solid #ddd;
      font-weight: bold;
    }

    table td {
      padding: 8px;
      border: 1px solid #ddd;
    }

    table tbody tr:nth-child(even) {
      background-color: #fafafa;
    }

    .summary {
      margin-top: 30px;
      padding: 15px;
      background-color: #f5f5f5;
      border: 1px solid #ddd;
    }

    .summary h3 {
      margin-bottom: 10px;
      font-size: 16px;
    }

    .summary p {
      margin-bottom: 5px;
      font-size: 14px;
    }

    .summary strong {
      display: inline-block;
      width: 150px;
    }

    .footer {
      margin-top: 30px;
      text-align: center;
      font-size: 10px;
      color: #999;
    }
  </style>
</head>

<body>
  <div class="header">
    <h1>Transaction Reports</h1>
    <p>Completed Transactions</p>
  </div>

  <div class="info-section">
    <p><strong>Generated On:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
    <p><strong>Period:</strong> {{ $periodLabel }}</p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Order Number</th>
        <th>Customer</th>
        <th>Email</th>
        <th>Total</th>
        <th>Payment Method</th>
        <th>Completed At</th>
      </tr>
    </thead>
    <tbody>
      @forelse($orders as $order)
      <tr>
        <td>{{ $order->order_number }}</td>
        <td>{{ $order->user->name ?? 'N/A' }}</td>
        <td>{{ $order->user->email ?? 'N/A' }}</td>
        <td>Rp {{ number_format($order->total, 0, ',', '.') }}</td>
        <td>{{ $order->paymentMethod->name ?? 'N/A' }}</td>
        <td>{{ $order->completed_at ? $order->completed_at->format('Y-m-d H:i:s') : 'N/A' }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="6" style="text-align: center; padding: 20px; color: #999;">
          No transactions found for the selected period
        </td>
      </tr>
      @endforelse
    </tbody>
  </table>

  <div class="summary">
    <h3>Summary</h3>
    <p><strong>Total Orders:</strong> {{ $summary['total_orders'] }}</p>
    <p><strong>Total Revenue:</strong> Rp {{ number_format($summary['total_revenue'], 0, ',', '.') }}</p>
  </div>

  <div class="footer">
    <p>Generated by Nurmi Kebun System</p>
  </div>
</body>

</html>